services:
  xinference:
    image: xinference
    container_name: xinference
    build: .
    command: bash launch_script.sh
    restart: always
    env_file:
      - hf.env
    volumes:
      - /srv/llm/xinference_cache/:/tmp/xinference/
#      - /cosybio/project/LLM/xinference_configs/:/cosybio/project/LLM/xinference_configs/
      - ./config.json:/config.json
      - /cosybio/archive/old_projects/LLM/xinference/:/.xinference/
    ports:
      - "9997:9997"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 4
              capabilities: [gpu]
